apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: 520864642809.dkr.ecr.us-east-1.amazonaws.com/my-vite-app:716ee3d3dbdc45ed82a5ca14835c43d7b05cc7a4
        ports:
        - containerPort: 80