apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: 520864642809.dkr.ecr.us-east-1.amazonaws.com/my-vite-app:c7c9223ced9ec2df63995ed76cab3a3a7d9da44a
        ports:
        - containerPort: 80