apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        # REPLACE THIS with your full ECR image URL. The tag 'latest' is a placeholder.
        image: 520864642809.dkr.ecr.us-east-1.amazonaws.com/my-vite-app:2e25ce09c4e771bc5af173420dffa2a1ef7020f6
        ports:
        - containerPort: 80